<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Original_Metamodel" nsURI="http://Original_Metamodel/1.0" nsPrefix="Original_Metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="A"/>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refA" eType="#//A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eAnnotations source="constraint2">
      <details key="value1" value="value1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D"/>
</ecore:EPackage>
