/*
 * generated by Xtext
 */
package monoge.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExtensionUiModule extends monoge.dsl.ui.AbstractExtensionUiModule {
	public ExtensionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
